export const tasks = [
  {
    id: 1,
    name: "Calvinball",
    group: "S.N.I.D.E.",
    status: "Active",
    level: 1,
    points: 3,
    description:
      "Show someone a better way to solve a mundane problem they are facing.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 2,
    name: "Thriddleblocky",
    group: "U.A. Masters Course",
    status: "Active",
    level: 3,
    points: 7,
    description: "Play at being a dolphin.",
    inProgress: 20,
    completed: 3,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 3,
    name: "Sheepshearing",
    group: "Journeymen",
    status: "Active",
    level: 0,
    points: 9,
    description: "Shear a sheep with sheer dedication.",
    inProgress: 20,
    completed: 100,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 4,
    name: "Seeing Beyond Sight Photo Challenge",
    group: "Analog",
    status: "Retired",
    level: 2,
    points: 10,
    description: "Some photos or some shit, I dunno.",
    inProgress: 20,
    completed: 45,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 5,
    name: "Placepoem",
    group: "Gestalt",
    status: "Active",
    level: 5,
    points: 3,
    description: "Poemin' in places.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 6,
    name: "Campaign Trail",
    group: "S.N.I.D.E.",
    status: "Pretired",
    level: 5,
    points: 3,
    description: "Beat up a politician in VR.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 7,
    name: "The Odyssey",
    group: "Gestalt",
    status: "Active",
    level: 5,
    points: 3,
    description:
      "This one might take a while and you'd better have a real good last one with your wife first.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 8,
    name: "Table Tennis with God",
    group: "Analog",
    status: "Retired",
    level: 5,
    points: 3,
    description:
      "God has been waiting all his infinity for this one match. It's all up to you, little man",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 9,
    name: "Punch the Moon",
    group: "University of Aesthematics",
    status: "Active",
    level: 5,
    points: 3,
    description: "Don't just stand there, PUNCH IT.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 10,
    name: "Don't Die Yet",
    group: "U.A. Masters Course",
    status: "Pretired",
    level: 5,
    points: 3,
    description:
      "Some say it's too easy. I say it's the hardest task of all...",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 11,
    name: "Calvinball",
    group: "S.N.I.D.E.",
    status: "Active",
    level: 1,
    points: 3,
    description:
      "Show someone a better way to solve a mundane problem they are facing.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 12,
    name: "Thriddleblocky",
    group: "U.A. Masters Course",
    status: "Active",
    level: 3,
    points: 7,
    description: "Play at being a dolphin.",
    inProgress: 20,
    completed: 3,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 13,
    name: "Sheepshearing",
    group: "Journeymen",
    status: "Active",
    level: 0,
    points: 9,
    description: "Shear a sheep with sheer dedication.",
    inProgress: 20,
    completed: 100,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 14,
    name: "Seeing Beyond Sight Photo Challenge",
    group: "Analog",
    status: "Retired",
    level: 2,
    points: 10,
    description: "Some photos or some shit, I dunno.",
    inProgress: 20,
    completed: 45,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 15,
    name: "Placepoem",
    group: "Gestalt",
    status: "Active",
    level: 5,
    points: 3,
    description: "Poemin' in places.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 16,
    name: "Campaign Trail",
    group: "S.N.I.D.E.",
    status: "Pretired",
    level: 5,
    points: 3,
    description: "Beat up a politician in VR.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 17,
    name: "The Odyssey",
    group: "Gestalt",
    status: "Active",
    level: 5,
    points: 3,
    description:
      "This one might take a while and you'd better have a real good last one with your wife first.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 18,
    name: "Table Tennis with God",
    group: "Analog",
    status: "Retired",
    level: 5,
    points: 3,
    description:
      "God has been waiting all his infinity for this one match. It's all up to you, little man",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 19,
    name: "Punch the Moon",
    group: "University of Aesthematics",
    status: "Active",
    level: 5,
    points: 3,
    description: "Don't just stand there, PUNCH IT.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 20,
    name: "Don't Die Yet",
    group: "U.A. Masters Course",
    status: "Pretired",
    level: 5,
    points: 3,
    description:
      "Some say it's too easy. I say it's the hardest task of all...",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 21,
    name: "Don't Die Yet",
    group: "U.A. Masters Course",
    status: "Pretired",
    level: 5,
    points: 3,
    description:
      "Some say it's too easy. I say it's the hardest task of all...",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 22,
    name: "Thriddleblocky",
    group: "U.A. Masters Course",
    status: "Active",
    level: 3,
    points: 7,
    description: "Play at being a dolphin.",
    inProgress: 20,
    completed: 3,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 23,
    name: "Sheepshearing",
    group: "Journeymen",
    status: "Active",
    level: 0,
    points: 9,
    description: "Shear a sheep with sheer dedication.",
    inProgress: 20,
    completed: 100,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 24,
    name: "Seeing Beyond Sight Photo Challenge",
    group: "Analog",
    status: "Retired",
    level: 2,
    points: 10,
    description: "Some photos or some shit, I dunno.",
    inProgress: 20,
    completed: 45,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 25,
    name: "Placepoem",
    group: "Gestalt",
    status: "Active",
    level: 5,
    points: 3,
    description: "Poemin' in places.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 26,
    name: "Campaign Trail",
    group: "S.N.I.D.E.",
    status: "Pretired",
    level: 5,
    points: 3,
    description: "Beat up a politician in VR.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 27,
    name: "The Odyssey",
    group: "Gestalt",
    status: "Active",
    level: 5,
    points: 3,
    description:
      "This one might take a while and you'd better have a real good last one with your wife first.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 28,
    name: "Table Tennis with God",
    group: "Analog",
    status: "Retired",
    level: 5,
    points: 3,
    description:
      "God has been waiting all his infinity for this one match. It's all up to you, little man",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 29,
    name: "Punch the Moon",
    group: "University of Aesthematics",
    status: "Active",
    level: 5,
    points: 3,
    description: "Don't just stand there, PUNCH IT.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 30,
    name: "Don't Die Yet",
    group: "U.A. Masters Course",
    status: "Pretired",
    level: 5,
    points: 3,
    description:
      "Some say it's too easy. I say it's the hardest task of all...",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 31,
    name: "Don't Die Yet",
    group: "U.A. Masters Course",
    status: "Pretired",
    level: 5,
    points: 3,
    description:
      "Some say it's too easy. I say it's the hardest task of all...",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 32,
    name: "Thriddleblocky",
    group: "U.A. Masters Course",
    status: "Active",
    level: 3,
    points: 7,
    description: "Play at being a dolphin.",
    inProgress: 20,
    completed: 3,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 33,
    name: "Sheepshearing",
    group: "Journeymen",
    status: "Active",
    level: 0,
    points: 9,
    description: "Shear a sheep with sheer dedication.",
    inProgress: 20,
    completed: 100,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 34,
    name: "Seeing Beyond Sight Photo Challenge",
    group: "Analog",
    status: "Retired",
    level: 2,
    points: 10,
    description: "Some photos or some shit, I dunno.",
    inProgress: 20,
    completed: 45,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 35,
    name: "Placepoem",
    group: "Gestalt",
    status: "Active",
    level: 5,
    points: 3,
    description: "Poemin' in places.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 36,
    name: "Campaign Trail",
    group: "S.N.I.D.E.",
    status: "Pretired",
    level: 5,
    points: 3,
    description: "Beat up a politician in VR.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 37,
    name: "The Odyssey",
    group: "Gestalt",
    status: "Active",
    level: 5,
    points: 3,
    description:
      "This one might take a while and you'd better have a real good last one with your wife first.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 38,
    name: "Table Tennis with God",
    group: "Analog",
    status: "Retired",
    level: 5,
    points: 3,
    description:
      "God has been waiting all his infinity for this one match. It's all up to you, little man",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 39,
    name: "Punch the Moon",
    group: "University of Aesthematics",
    status: "Active",
    level: 5,
    points: 3,
    description: "Don't just stand there, PUNCH IT.",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 40,
    name: "Don't Die Yet",
    group: "U.A. Masters Course",
    status: "Pretired",
    level: 5,
    points: 3,
    description:
      "Some say it's too easy. I say it's the hardest task of all...",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
  {
    id: 41,
    name: "Don't Die Yet",
    group: "U.A. Masters Course",
    status: "Pretired",
    level: 5,
    points: 3,
    description:
      "Some say it's too easy. I say it's the hardest task of all...",
    inProgress: 20,
    completed: 15,
    minPlayers: 5,
    maxPlayers: 10,
  },
];
