// import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { ThemeProvider } from "@/context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en" className="dark">
        <body className={inter.className}>
          <div className="flex flex-col h-screen">
            <Navbar />
            <main className="flex-grow overflow-auto">{children}</main>
          </div>
        </body>
      </html>
    </ThemeProvider>
  );
}
