// import { groups } from "../groups/groups-data";
// import { tasks } from "../tasks/tasks-data";

// Columns:
// id int AI PK
// username varchar(255)
// password varchar(60)
// email varchar(255)
// level smallint
// points mediumint
// terms text
// description text
// image_path varchar(255)
// created_at timestamp
// group_id int
// flags int
// is_banned tinyint(1)
// location varchar(255)
// theme varchar(255)
// votes int
export const players = [
  {
    id: 1,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 2,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 3,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 4,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 5,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 6,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 7,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 8,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 9,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 10,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
  {
    id: 11,
    name: "Pixie",
    avatar: "fakeimage.jpg",
    description: "I am the prophet of the new era.",
    group: "U.A. Masters Course",
    rank: "Prophet",
    level: 8,
    points: 5498,
    lastLogin: "October 11th, 2020",
    completedTasks: [1, 3, 15],
    createdTasks: [3, 15, 23],
    terms: [
      "flexible",
      "pdx",
      "senator",
      "bjork",
      "manicpixiedreamperson",
      "ggyeah",
      "lovely",
      "gleek",
    ],
    // friends: ,
    // foes:,
    // votesReceived:, // since it's more than just a count but shows where and when and links to the task, this will probably have to be stored in tasks like votes: [users]. same for votesCast, favorites. comments seem even more complex
    // votesCast:,
    // photos:,
    // favorites:,
    comments: [
      "I wish I could have met you. I'll let you know next time I'm in the UK!!",
      "Bah. I will get in the last word. But I will tell you and everyone else so you can come play the new game. Also, if anyone is still here, they should be helping me with it :D",
      "That is a big deal. Welcome to the future :D",
    ],
  },
];
